<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Henrietta Kadi Tettey-Tawiah">

<title>Understanding 4th Grade Math Percent Correct through Student and Teacher Characteristics: A Regression Study using TIMSS 2023</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="ESRM 6990V_files/libs/clipboard/clipboard.min.js"></script>
<script src="ESRM 6990V_files/libs/quarto-html/quarto.js"></script>
<script src="ESRM 6990V_files/libs/quarto-html/popper.min.js"></script>
<script src="ESRM 6990V_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ESRM 6990V_files/libs/quarto-html/anchor.min.js"></script>
<link href="ESRM 6990V_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ESRM 6990V_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ESRM 6990V_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ESRM 6990V_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ESRM 6990V_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="ESRM 6990V_files/libs/table1-1.0/table1_defaults.css" rel="stylesheet">

<script src="ESRM 6990V_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="ESRM 6990V_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Understanding 4th Grade Math Percent Correct through Student and Teacher Characteristics: A Regression Study using TIMSS 2023</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Henrietta Kadi Tettey-Tawiah </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p>(A Regression-Based Investigation of Student- and Teacher-Level Influences on Math Performance in TIMSS 2023)</p>
<section id="introduction-research-scenario-and-research-questions" class="level2">
<h2 class="anchored" data-anchor-id="introduction-research-scenario-and-research-questions">Introduction: Research Scenario and Research Questions</h2>
<p>I would want to investigate the performance of students in the United States of America (USA) and Canada based on the 2023 <a href="https://timss2023.org/data">TIMSS</a> (Trends in International Mathematics and Science Study) dataset. TIMSS is an international measure of mathematics and science achievements of fourth and eighth grade students. The TIMSS is conducted every <a href="https://www.iea.nl/studies/iea/timss">four years</a> at the fourth and eighth grade levels. In addition to standardized achievement tests in math and science, TIMSS also collects information of school resources, teacher training/characteristics, home background as well as curriculum implementation. A total of 64 countries participated in the 2023 cycle of TIMSS. This analysis focuses on math performance of 4th grade students using their percentage correct on the TIMSS math achievement test. In this study, student level factors, home factors as well as teacher-level factors are explored to identify their respective impacts on an individual student’s math test score. Specifically, this research seeks to answer the following:</p>
<ol type="1">
<li>What proportion of variation the performance of a student on the math test is explained by factors such as gender, country, student confidence among others?
<ul>
<li>Are here are any country-level and/or sex differences in math percentage scores? (“How does math performance vary across countries and sexes?”)</li>
</ul></li>
<li>How do various teacher characteristics influence student’s score on the math test?
<ul>
<li>Are they are differences in students’ math percentage scores across levels of age and formal education completed?</li>
</ul></li>
</ol>
<p>This report is organized as follows:</p>
<ol type="1">
<li>Introduction and Research Question</li>
<li>Data Analysis
<ul>
<li><p>Student-Level Analysis</p>
<ul>
<li><p>Data Preparation</p></li>
<li><p>Descriptive Statistics and Visualization</p></li>
<li><p>Step-wise Regression Analysis</p>
<p>- Difference-in-Differences Analysis</p></li>
</ul></li>
<li><p>Teacher-Level Analysis</p>
<ul>
<li><p>Data Preparation</p></li>
<li><p>Descriptive Statistics and Visualization</p></li>
<li><p>Step-wise Regression Analysis</p>
<p>- Marginal Contrast Analysis</p></li>
</ul></li>
</ul></li>
</ol>
</section>
<section id="data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis">Data Analysis</h2>
<section id="student-level-analysis" class="level3">
<h3 class="anchored" data-anchor-id="student-level-analysis">Student-Level Analysis</h3>
<p>The dataset used in this contained a total of 18369 participants after data cleaning. The dataset had a total of 373 variables but only 13 are reported below:</p>
<ul>
<li><p><strong>Student_ID:</strong> Student Identifier</p></li>
<li><p><strong>Country:</strong> Country of Participation (CAN = 1, USA = 2)</p></li>
<li><p><strong>Sex:</strong> Sex/Gender (1 = Girl, 2 = Boy)</p></li>
<li><p><strong>Age :</strong> Age of student</p></li>
<li><p><strong>Number_of_Home_Study_Supports:</strong> Derived from subscale measuring resources available to the student at home.</p></li>
<li><p><strong>Disorderly_Behavior:</strong> Scale score from the subscale measuring disorderly behavior during math lessons.</p></li>
<li><p><strong>Instructional_Clarity:</strong> Scale score from the subscale measuring instructional clarity in mathematics lessons.</p></li>
<li><p><strong>Digital_Self_Efficacy:</strong> Scale score from the subscale measuring digital self-efficacy.</p></li>
<li><p><strong>Sense_of_School_Belonging:</strong> Scale score from the subscale measuring students sense of school belonging.</p></li>
<li><p><strong>Student_Bullying:</strong> Scale score from the subscale measuring student bullying.</p></li>
<li><p><strong>Like_Learning_Math:</strong> Scale score from the subscale measuring if students like learning mathematics.</p></li>
<li><p><strong>Confident_in_Math:</strong> Scale score from the subscale measuring students confidence in mathematics.</p></li>
<li><p><strong>Math_Percent_Correct</strong>: Students’ percent correct on the 2023 TIMSS Math Achievement Test.</p></li>
</ul>
<p>The scale scores reported were derived following several steps including; item parameter estimation, item fit evaluation among others <span class="citation" data-cites="yin2024">(<a href="#ref-yin2024" role="doc-biblioref">Yin and Reynolds 2024</a>)</span>.</p>
<section id="data-preparation" class="level4">
<h4 class="anchored" data-anchor-id="data-preparation">Data Preparation</h4>
<p>The data preparation stage began with renaming the columns in the <code>Home_Student</code> dataset with more descriptive names. After this, the dataset is cleaned by removing any rows containing missing values resulting in a final dataset with only complete cases as well as specifying categorical variables and dropping any unused levels.</p>
</section>
<section id="descriptive-statistics" class="level4">
<h4 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h4>
<p>The total sample size of the Canada and U.S.A. 4th grade students was 22806. However, due to non-response, the sample size used for this analysis was 18369; 9351 girls and 9018 boys. There were more Canadian 4th Grade students compared to the U.S.A. in the sample (<a href="#fig-Country-by-Sex" class="quarto-xref">Figure&nbsp;1</a>). The overall mean age was 10 years (S.D. = 0.390) and the average sample class score was 52% (S.D. = 0.390). About 51% of the entire sample was female with Canada accounting for about 52% of the total population of females. A comprehensive summary of the sample information can be seen in <a href="#tbl-sample-descriptives" class="quarto-xref">Table&nbsp;1</a>. The distribution of the math scores for each country and sex subgroup can be described as bi-modal as shown in <a href="#fig-dist-of-math-score" class="quarto-xref">Figure&nbsp;2</a>. As shown in <a href="#fig-dist-of-math-score-country-sex-home-support" class="quarto-xref">Figure&nbsp;3</a>, it can be observed that U.S.A students had a higher Math score average with boys also having a higher average score. Students who had access to both their own rooms and internet access seemed to have a better average score compared to those who had neither (<a href="#fig-dist-of-math-score-country-sex-home-support-4" class="quarto-xref">Figure&nbsp;3 (d)</a>). As shown in <a href="#fig-Correlations" class="quarto-xref">Figure&nbsp;4</a>, the correlations between the predictors and math score were in the moderate to low range.</p>
<div class="cell">
<div id="tbl-sample-descriptives" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sample-descriptives-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Sample Descriptive Statistics
</figcaption>
<div aria-describedby="tbl-sample-descriptives-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="Rtable1">
<table class="Rtable1 do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th class="rowlabel firstrow lastrow" data-quarto-table-cell-role="th"></th>
<th class="firstrow lastrow" data-quarto-table-cell-role="th"><span class="stratlabel">CAN<br>
<span class="stratn">(N=10616)</span></span></th>
<th class="firstrow lastrow" data-quarto-table-cell-role="th"><span class="stratlabel">USA<br>
<span class="stratn">(N=7753)</span></span></th>
<th class="firstrow lastrow" data-quarto-table-cell-role="th"><span class="stratlabel">Overall<br>
<span class="stratn">(N=18369)</span></span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowlabel firstrow">Mathematics Percent Correct Points Scored</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Mean (SD)</td>
<td>49.8 (22.9)</td>
<td>55.0 (24.9)</td>
<td>52.0 (23.9)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">50.0 [0, 100]</td>
<td class="lastrow">56.5 [0, 100]</td>
<td class="lastrow">52.0 [0, 100]</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow">Students Age</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Mean (SD)</td>
<td>9.91 (0.342)</td>
<td>10.2 (0.383)</td>
<td>10.0 (0.390)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">9.92 [6.42, 11.8]</td>
<td class="lastrow">10.2 [8.58, 12.4]</td>
<td class="lastrow">10.0 [6.42, 12.4]</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Sex</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Girl</td>
<td>5491 (51.7%)</td>
<td>3860 (49.8%)</td>
<td>9351 (50.9%)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Boy</td>
<td class="lastrow">5125 (48.3%)</td>
<td class="lastrow">3893 (50.2%)</td>
<td class="lastrow">9018 (49.1%)</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow">Country</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">CAN</td>
<td>10616 (100%)</td>
<td>0 (0%)</td>
<td>10616 (57.8%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">USA</td>
<td class="lastrow">0 (0%)</td>
<td class="lastrow">7753 (100%)</td>
<td class="lastrow">7753 (42.2%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Disorderly Behavior during Math Lessons/SCL</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Mean (SD)</td>
<td>9.63 (1.60)</td>
<td>9.54 (1.74)</td>
<td>9.59 (1.66)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">9.67 [6.16, 14.8]</td>
<td class="lastrow">9.67 [6.16, 14.8]</td>
<td class="lastrow">9.67 [6.16, 14.8]</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow">Student Bullying/SCL</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Mean (SD)</td>
<td>9.76 (1.72)</td>
<td>9.90 (1.88)</td>
<td>9.82 (1.79)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">9.50 [3.81, 12.8]</td>
<td class="lastrow">9.71 [3.81, 12.8]</td>
<td class="lastrow">9.71 [3.81, 12.8]</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Instructional Clarity in Mathematics Lessons/SCL</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Mean (SD)</td>
<td>10.1 (1.86)</td>
<td>9.95 (1.97)</td>
<td>10.0 (1.91)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">10.6 [2.46, 12.1]</td>
<td class="lastrow">9.79 [2.46, 12.1]</td>
<td class="lastrow">9.79 [2.46, 12.1]</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow">Digital Self-Efficacy/SCL</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Mean (SD)</td>
<td>10.4 (1.91)</td>
<td>10.1 (1.88)</td>
<td>10.2 (1.91)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">10.1 [3.27, 14.0]</td>
<td class="lastrow">9.68 [3.27, 14.0]</td>
<td class="lastrow">10.1 [3.27, 14.0]</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Students Sense of School Belonging/SCL</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Mean (SD)</td>
<td>9.93 (1.96)</td>
<td>9.65 (1.91)</td>
<td>9.81 (1.95)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">9.68 [3.61, 12.9]</td>
<td class="lastrow">9.68 [3.61, 12.9]</td>
<td class="lastrow">9.68 [3.61, 12.9]</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow">Students Like Learning Mathematics/SCL</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Mean (SD)</td>
<td>9.90 (1.95)</td>
<td>9.86 (2.06)</td>
<td>9.88 (2.00)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">9.76 [4.93, 12.6]</td>
<td class="lastrow">9.76 [4.93, 12.6]</td>
<td class="lastrow">9.76 [4.93, 12.6]</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Students Confident in Mathematics/SCL</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Mean (SD)</td>
<td>10.2 (2.00)</td>
<td>10.1 (2.12)</td>
<td>10.1 (2.05)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">9.81 [3.70, 14.2]</td>
<td class="lastrow">9.80 [3.70, 14.2]</td>
<td class="lastrow">9.81 [3.70, 14.2]</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow">Number_of_Home_Study_Supports</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Neither Own Room nor Access to the Internet</td>
<td>284 (2.7%)</td>
<td>232 (3.0%)</td>
<td>516 (2.8%)</td>
</tr>
<tr class="even">
<td class="rowlabel">Either Own Room or Access to the Internet</td>
<td>2617 (24.7%)</td>
<td>2287 (29.5%)</td>
<td>4904 (26.7%)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Both Own Room and Access to the Internet</td>
<td class="lastrow">7715 (72.7%)</td>
<td class="lastrow">5234 (67.5%)</td>
<td class="lastrow">12949 (70.5%)</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-Country-by-Sex" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Country-by-Sex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-Country-by-Sex-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Country-by-Sex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Number of sudents by Country and Sex
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dist-of-math-score" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dist-of-math-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-dist-of-math-score-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dist-of-math-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Histogram of the Distribution of Math Scores
</figcaption>
</figure>
</div>
</div>
</div>
<div id="fig-dist-of-math-score-country-sex-home-support" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dist-of-math-score-country-sex-home-support-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-dist-of-math-score-country-sex-home-support" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-dist-of-math-score-country-sex-home-support-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-dist-of-math-score-country-sex-home-support-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-dist-of-math-score-country-sex-home-support-1.png" class="img-fluid figure-img" data-ref-parent="fig-dist-of-math-score-country-sex-home-support" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-dist-of-math-score-country-sex-home-support-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Boxplots of the Distribution of Scores by Country
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-dist-of-math-score-country-sex-home-support" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-dist-of-math-score-country-sex-home-support-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-dist-of-math-score-country-sex-home-support-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-dist-of-math-score-country-sex-home-support-2.png" class="img-fluid figure-img" data-ref-parent="fig-dist-of-math-score-country-sex-home-support" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-dist-of-math-score-country-sex-home-support-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Boxplots of the Distribution of Scores by Sex
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-dist-of-math-score-country-sex-home-support" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-dist-of-math-score-country-sex-home-support-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-dist-of-math-score-country-sex-home-support-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-dist-of-math-score-country-sex-home-support-3.png" class="img-fluid figure-img" data-ref-parent="fig-dist-of-math-score-country-sex-home-support" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-dist-of-math-score-country-sex-home-support-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Boxplots of the Distribution of Scores by Country and Sex
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-dist-of-math-score-country-sex-home-support" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-dist-of-math-score-country-sex-home-support-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-dist-of-math-score-country-sex-home-support-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-dist-of-math-score-country-sex-home-support-4.png" class="img-fluid figure-img" data-ref-parent="fig-dist-of-math-score-country-sex-home-support" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-dist-of-math-score-country-sex-home-support-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Boxplots of the Distribution of Scores by Home Support
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dist-of-math-score-country-sex-home-support-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Boxplots of the the Distribution of Scores by Country, Sex and Home Support
</figcaption>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-Correlations" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Correlations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-Correlations-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Correlations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Correlation Heatmap for Student-Level Analysis
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="regression-analysis" class="level4">
<h4 class="anchored" data-anchor-id="regression-analysis">Regression Analysis</h4>
<p>A step-wise regression model was estimated to evaluate whether the independent variables <em>(Country, Sex, Age, Disorderly_Behavior, Instructional_Clarity, Digital_Self_Efficacy, Student_Bullying, Like_Learning_Math, Confident_in_Math, and Number_of_Home_Study_Supports)</em> could predict the dependent variable, <em>Math_Percent_Correct</em> . The linear relationship between independent variables and math score was found to be statistically significant <span class="math inline">\(F(11, 18357) = 439.39,\ p &lt; .001\)</span>. Appoximately <span class="math inline">\(21\%\)</span> of the total variation in math percent score was account for by its linear relationship with the predictors, <span class="math inline">\(R^2 = .21,\ R^2_{adj}=.21\)</span>. Among the predictors, instructional clarity had a statistically non-significant and negative effect on math percentage value <span class="math inline">\((\beta = -.16,\ p &lt; .001)\)</span>, suggesting that greater instructional clarity was not associated with higher math percent values in this model over and above all other predictors. The effect of Country (U.S.A.) was statistically significant and positive <span class="math inline">\((\beta = 5.58,\ p &lt; .001)\)</span>, suggesting that holding all other predictors unchanged, 4th grade students scored 5.58% higher than those in Canada. The effect of Sex (boy) was also statistically significant and positive <span class="math inline">\((\beta = 2.01,\ p &lt; .001)\)</span>, suggesting that controlling for all other predictors, boys in the 4th grade scored 2.01% higher than girls. Interestingly, Like_Learning_Math was found to have statistically significant and negative effect on math percent score <span class="math inline">\((\beta = -.97,\ p &lt; .001)\)</span>. This suggests that partialling out the effects of all other predictors, and a unit increase in a student whether a student likes learning math results in a -0.97% decrease in math percent score. All other predictors in the model had a statistically significant and positive effect on math percent score. This suggests that holding all other predictions unchanged, an increase in their respective values is expected lead to an increase in math percentage score.</p>
<p>The details of the results from the step-wise analysis are presented in <a href="#tbl-Initial-regression-for-student-data" class="quarto-xref">Table&nbsp;2</a>. The predictor Confident_in_Math had the largest effect on the math percent score followed by Number_of_Home_Study_Supports_Either <a href="#tbl-Initial-regression-for-student-data-4" class="quarto-xref">Table&nbsp;2 (d)</a>. The predictors used in this analysis do not exhibit multicollinearity as shown in <a href="#tbl-Initial-regression-for-student-data-3" class="quarto-xref">Table&nbsp;2 (c)</a>. A look at the residual plots in <a href="#fig-residual-std_reg_initial" class="quarto-xref">Figure&nbsp;5</a> show a slight non-linearity with possible non-normality from the Q-Q plot.</p>
<div class="cell">
<div id="tbl-Initial-regression-for-student-data" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Initial-regression-for-student-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Student-Level Regression Analysis
</figcaption>
<div aria-describedby="tbl-Initial-regression-for-student-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="tbl-Initial-regression-for-student-data-1" class="table table-striped table-hover table-condensed do-not-create-environment quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-Initial-regression-for-student-data-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Student Level Regression Coefficients
</figcaption>
<div aria-describedby="tbl-Initial-regression-for-student-data-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-Initial-regression-for-student-data-1" class="table table-striped table-hover table-condensed do-not-create-environment caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-35.487</td>
<td style="text-align: right;">4.634</td>
<td style="text-align: right;">-7.658</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">CountryUSA</td>
<td style="text-align: right;">5.584</td>
<td style="text-align: right;">0.346</td>
<td style="text-align: right;">16.123</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SexBoy</td>
<td style="text-align: right;">2.006</td>
<td style="text-align: right;">0.320</td>
<td style="text-align: right;">6.279</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">1.112</td>
<td style="text-align: right;">0.437</td>
<td style="text-align: right;">2.546</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Disorderly_Behavior</td>
<td style="text-align: right;">0.603</td>
<td style="text-align: right;">0.102</td>
<td style="text-align: right;">5.903</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Instructional_Clarity</td>
<td style="text-align: right;">-0.164</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">-1.779</td>
<td style="text-align: right;">0.075</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Digital_Self_Efficacy</td>
<td style="text-align: right;">1.054</td>
<td style="text-align: right;">0.087</td>
<td style="text-align: right;">12.060</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Student_Bullying</td>
<td style="text-align: right;">1.021</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">10.582</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Like_Learning_Math</td>
<td style="text-align: right;">-0.968</td>
<td style="text-align: right;">0.098</td>
<td style="text-align: right;">-9.892</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Confident_in_Math</td>
<td style="text-align: right;">4.773</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">50.695</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number_of_Home_Study_SupportsEither Own Room or Access to the Internet</td>
<td style="text-align: right;">8.055</td>
<td style="text-align: right;">0.990</td>
<td style="text-align: right;">8.140</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number_of_Home_Study_SupportsBoth Own Room and Access to the Internet</td>
<td style="text-align: right;">10.088</td>
<td style="text-align: right;">0.965</td>
<td style="text-align: right;">10.451</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</div>
<div class="cell-output-display">
<div id="tbl-Initial-regression-for-student-data-2" class="table table-striped table-hover table-condensed do-not-create-environment quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-Initial-regression-for-student-data-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Student Level Model Summary Statistics
</figcaption>
<div aria-describedby="tbl-Initial-regression-for-student-data-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-Initial-regression-for-student-data-2" class="table table-striped table-hover table-condensed do-not-create-environment caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">adj.r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.208</td>
<td style="text-align: right;">0.208</td>
<td style="text-align: right;">21.298</td>
<td style="text-align: right;">439.394</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">-82242.15</td>
<td style="text-align: right;">164510.3</td>
<td style="text-align: right;">164611.9</td>
<td style="text-align: right;">8326823</td>
<td style="text-align: right;">18357</td>
<td style="text-align: right;">18369</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</div>
<div class="cell-output-display">
<div id="tbl-Initial-regression-for-student-data-3" class="table table-striped table-hover table-condensed do-not-create-environment quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-Initial-regression-for-student-data-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Variance Inflation Factors for Student Level Analysis
</figcaption>
<div aria-describedby="tbl-Initial-regression-for-student-data-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-Initial-regression-for-student-data-3" class="table table-striped table-hover table-condensed do-not-create-environment caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">GVIF</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">GVIF^(1/(2*Df))</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Country</td>
<td style="text-align: right;">1.185</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.088</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sex</td>
<td style="text-align: right;">1.033</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.017</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">1.174</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.084</td>
</tr>
<tr class="even">
<td style="text-align: left;">Disorderly_Behavior</td>
<td style="text-align: right;">1.160</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.077</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Instructional_Clarity</td>
<td style="text-align: right;">1.254</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.120</td>
</tr>
<tr class="even">
<td style="text-align: left;">Digital_Self_Efficacy</td>
<td style="text-align: right;">1.123</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.060</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Student_Bullying</td>
<td style="text-align: right;">1.213</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.102</td>
</tr>
<tr class="even">
<td style="text-align: left;">Like_Learning_Math</td>
<td style="text-align: right;">1.551</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.245</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Confident_in_Math</td>
<td style="text-align: right;">1.508</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.228</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number_of_Home_Study_Supports</td>
<td style="text-align: right;">1.039</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.010</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</div>
<div class="cell-output-display">
<div id="tbl-Initial-regression-for-student-data-4" class="table table-striped table-hover table-condensed do-not-create-environment quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-Initial-regression-for-student-data-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Standardized Regression Coefficients for Student Level Analysis
</figcaption>
<div aria-describedby="tbl-Initial-regression-for-student-data-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-Initial-regression-for-student-data-4" class="table table-striped table-hover table-condensed do-not-create-environment caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">-0.194</td>
</tr>
<tr class="even">
<td style="text-align: left;">Country_USA</td>
<td style="text-align: right;">0.117</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sex_Boy</td>
<td style="text-align: right;">0.042</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">0.018</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Disorderly_Behavior</td>
<td style="text-align: right;">0.042</td>
</tr>
<tr class="even">
<td style="text-align: left;">Instructional_Clarity</td>
<td style="text-align: right;">-0.013</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Digital_Self_Efficacy</td>
<td style="text-align: right;">0.084</td>
</tr>
<tr class="even">
<td style="text-align: left;">Student_Bullying</td>
<td style="text-align: right;">0.077</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Like_Learning_Math</td>
<td style="text-align: right;">-0.081</td>
</tr>
<tr class="even">
<td style="text-align: left;">Confident_in_Math</td>
<td style="text-align: right;">0.409</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number_of_Home_Study_Supports_Either</td>
<td style="text-align: right;">0.168</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number_of_Home_Study_Supports_Both</td>
<td style="text-align: right;">0.211</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-residual-std_reg_initial" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-residual-std_reg_initial-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-residual-std_reg_initial-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-residual-std_reg_initial-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Residual Plots for the Student Level Regression Model
</figcaption>
</figure>
</div>
</div>
</div>
<section id="difference-in-difference-analysis-on-combinations-of-sex-and-country" class="level5">
<h5 class="anchored" data-anchor-id="difference-in-difference-analysis-on-combinations-of-sex-and-country">Difference-in-Difference Analysis on Combinations of Sex and Country</h5>
<p>This section of the analysis focuses on whether there are sex and/or country specific differences in the performance of the 4th grade students on the TIMSS math test. To do this, a differences-in-differences analysis was performed on various combinations of the country and sex variables. From <a href="#tbl-Differences-in-Differences-tables" class="quarto-xref">Table&nbsp;3</a> and <a href="#fig-Differences-in-Differences-fiqures" class="quarto-xref">Figure&nbsp;6</a>, it can be observed that holding all other predictors unchanged, the predicted average math percent value for a typical 4th grade student in the U.S.A is higher than in Canada. Also, a typical Canadian or U.S.A 4th grade boy seem to have a higher predicted average math percent score than their girl counterparts. A marginal contrast analysis (<a href="#tbl-Differences-in-Differences-tables-2" class="quarto-xref">Table&nbsp;3 (b)</a>) was further performed to evaluate if these differences were statistically significant. This analysis revealed that the differences in predicted scores across all combinations of sex and country were statistically significant. In the U.S.A, boys had significantly higher predicted math scores than girls <span class="math inline">\((\text{difference}= 2.01,\ 95\%  \text{ CI } [1.38, 2.63],\ t(18357) = 6.28,\ p &lt; .001)\)</span>. Boys in Canada also had a significantly higher predicted math scores than girls<span class="math inline">\((\text{difference}= 2.01,\ 95\%  \text{ CI } [1.38, 2.63],\ t(18357) = 6.28,\ p &lt; .001)\)</span>. When comparing the average predicted scores of girls in the U.S.A. to those in Canada, the girls in the U.S.A had a significantly higher score <span class="math inline">\((\text{difference}= 5.58,\ 95\%   \text{ CI } [4.91, 6.26],\ t(18357) = 16.12,\ p &lt; .001)\)</span>. Similarly, girls in the U.S.A. also outperformed the boys in Canada <span class="math inline">\((\text{difference}= -3.58,\ 95\%   \text{ CI } [–4.51, –2.65],\ t(18357) = -7.53,\ p &lt; .001)\)</span>. Additionally, boys in the U.S.A scored significantly higher than the boys in Canada <span class="math inline">\((\text{difference}= 5.58,\ 95\%   \text{ CI } [4.91, 6.26],\ t(18357) = 16.12,\ p &lt; .001)\)</span>. In the same vein, boys in the U.S.A. also outperformed the girls in Canada by the largest margin <span class="math inline">\((\text{difference}= 7.59,\ 95\%   \text{ CI } [6.67, 8.51],\ t(18357) = 16.25,\ p &lt; .001)\)</span>.</p>
<p>These findings suggest that while gender differences exist, the national level factors may play a more substantial role in the TIMSS math percent score of 4th grade students. Further research should explore some potential national level contributors like curriculum standards.</p>
<div class="cell">
<div id="tbl-Differences-in-Differences-tables" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Differences-in-Differences-tables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Differences-in-Differences Analysis
</figcaption>
<div aria-describedby="tbl-Differences-in-Differences-tables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="tbl-Differences-in-Differences-tables-1" class="table table-striped table-hover table-condensed do-not-create-environment quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-Differences-in-Differences-tables-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Estimated Marginal Means of Predicted Math Scores by Sex and Country
</figcaption>
<div aria-describedby="tbl-Differences-in-Differences-tables-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-Differences-in-Differences-tables-1" class="table table-striped table-hover table-condensed do-not-create-environment caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Sex</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Country</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI_low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI_high</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Girl</td>
<td style="text-align: left;">CAN</td>
<td style="text-align: right;">45.416</td>
<td style="text-align: right;">0.400</td>
<td style="text-align: right;">44.632</td>
<td style="text-align: right;">46.199</td>
<td style="text-align: right;">113.611</td>
<td style="text-align: right;">18357</td>
</tr>
<tr class="even">
<td style="text-align: left;">Girl</td>
<td style="text-align: left;">USA</td>
<td style="text-align: right;">51.000</td>
<td style="text-align: right;">0.422</td>
<td style="text-align: right;">50.172</td>
<td style="text-align: right;">51.828</td>
<td style="text-align: right;">120.766</td>
<td style="text-align: right;">18357</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Boy</td>
<td style="text-align: left;">CAN</td>
<td style="text-align: right;">47.422</td>
<td style="text-align: right;">0.404</td>
<td style="text-align: right;">46.630</td>
<td style="text-align: right;">48.214</td>
<td style="text-align: right;">117.353</td>
<td style="text-align: right;">18357</td>
</tr>
<tr class="even">
<td style="text-align: left;">Boy</td>
<td style="text-align: left;">USA</td>
<td style="text-align: right;">53.006</td>
<td style="text-align: right;">0.422</td>
<td style="text-align: right;">52.179</td>
<td style="text-align: right;">53.833</td>
<td style="text-align: right;">125.643</td>
<td style="text-align: right;">18357</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</div>
<div class="cell-output-display">
<div id="tbl-Differences-in-Differences-tables-2" class="table table-striped table-hover table-condensed do-not-create-environment quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-Differences-in-Differences-tables-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Pairwise Contrasts of Predicted Math Scores by Sex and Country
</figcaption>
<div aria-describedby="tbl-Differences-in-Differences-tables-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-Differences-in-Differences-tables-2" class="table table-striped table-hover table-condensed do-not-create-environment caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Level1</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Level2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI_low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">CI_high</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Girl, USA</td>
<td style="text-align: left;">Girl, CAN</td>
<td style="text-align: right;">5.584</td>
<td style="text-align: right;">0.346</td>
<td style="text-align: right;">4.905</td>
<td style="text-align: right;">6.263</td>
<td style="text-align: right;">16.123</td>
<td style="text-align: right;">18357</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Boy, CAN</td>
<td style="text-align: left;">Girl, CAN</td>
<td style="text-align: right;">2.006</td>
<td style="text-align: right;">0.320</td>
<td style="text-align: right;">1.380</td>
<td style="text-align: right;">2.633</td>
<td style="text-align: right;">6.279</td>
<td style="text-align: right;">18357</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Boy, USA</td>
<td style="text-align: left;">Girl, CAN</td>
<td style="text-align: right;">7.590</td>
<td style="text-align: right;">0.467</td>
<td style="text-align: right;">6.675</td>
<td style="text-align: right;">8.506</td>
<td style="text-align: right;">16.249</td>
<td style="text-align: right;">18357</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Boy, CAN</td>
<td style="text-align: left;">Girl, USA</td>
<td style="text-align: right;">-3.577</td>
<td style="text-align: right;">0.475</td>
<td style="text-align: right;">-4.509</td>
<td style="text-align: right;">-2.646</td>
<td style="text-align: right;">-7.527</td>
<td style="text-align: right;">18357</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Boy, USA</td>
<td style="text-align: left;">Girl, USA</td>
<td style="text-align: right;">2.006</td>
<td style="text-align: right;">0.320</td>
<td style="text-align: right;">1.380</td>
<td style="text-align: right;">2.633</td>
<td style="text-align: right;">6.279</td>
<td style="text-align: right;">18357</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Boy, USA</td>
<td style="text-align: left;">Boy, CAN</td>
<td style="text-align: right;">5.584</td>
<td style="text-align: right;">0.346</td>
<td style="text-align: right;">4.905</td>
<td style="text-align: right;">6.263</td>
<td style="text-align: right;">16.123</td>
<td style="text-align: right;">18357</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-Differences-in-Differences-fiqures" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Differences-in-Differences-fiqures-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-Differences-in-Differences-fiqures-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Differences-in-Differences-fiqures-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Estimated Marginal Means of Predicted Math Scores by Sex and Country
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="teacher-level-analysis" class="level3">
<h3 class="anchored" data-anchor-id="teacher-level-analysis">Teacher-Level Analysis</h3>
<p>The dataset used in this contained a total of 18194 participants after data cleaning. The dataset had a total of 538 variables but only 14 are reported below:</p>
<ul>
<li><p><strong>Teacher_ID:</strong> Teacher Identifier</p></li>
<li><p><strong>Years_Teaching:</strong> Years teacher has been teaching</p></li>
<li><p><strong>Sex:</strong> Sex/Gender of teacher (1: Female; 2: Male; 3: Other)</p></li>
<li><p><strong>Age:</strong> Age of Teacher (1: Under 25; 2: 25–29; 3: 30–39; 4: 40–49; 5: 50–59; 6: 60 or more)</p></li>
<li><p><strong>Formal_Educ:</strong> Level of formal education teacher has completed (1: Did not complete Upper secondary education—ISCED Level 3; 2: Upper secondary education—ISCED Level 3 (have not completed postsecondary or tertiary education); 3: Post-secondary, non-tertiary education—ISCED Level 4; 4: Short-cycle tertiary education—ISCED Level 5; 5: Bachelor’s or equivalent level—ISCED Level 6; 6: Master’s or equivalent level—ISCED Level 7; 7: Doctor or equivalent level—ISCED Level 8)</p></li>
<li><p><strong>Class_Size:</strong> Number of students in the class.</p></li>
<li><p><strong>Homework_Freq:</strong> How often math homework is assigned (1: I do not assign mathematics homework; 2: Less than once a week; 3: 1 or 2 times a week; 4: 3 or 4 times a week; 5: Every day)</p></li>
<li><p><strong>Academic_Success:</strong> Scale score from the subscale measuring school emphasis on academic success-teacher.</p></li>
<li><p><strong>Safe_Orderly_Schools :</strong> Scale score from the subscale measuring safe and orderly schools-teacher.</p></li>
<li><p><strong>Job_Satis :</strong> Scale score from the subscale measuring teachers job satisfaction.</p></li>
<li><p><strong>Student_not_Ready:</strong> Scale score from the subscale measuring teaching limited by student not ready.</p></li>
<li><p><strong>TMath_Major :</strong> Teachers majored in education and mathematics (1: Major in Edu and Math; 2: Major in Edu but not Math; 3: Major in Math but not Edu; 4: All other Majors; 5: No Formal Edu Beyond Upper Secondary).</p></li>
<li><p><strong>Instruction_Hours:</strong> Mathematics instruction hours per week</p></li>
<li><p><strong>Math_Percent_Correct</strong>: Students’ percent correct on the 2023 TIMSS Math Achievement Test.</p></li>
</ul>
<p>The scale scores reported were derived following several steps including; item parameter estimation, item fit evaluation among others <span class="citation" data-cites="yin2024">(<a href="#ref-yin2024" role="doc-biblioref">Yin and Reynolds 2024</a>)</span>.</p>
<section id="data-preparation-1" class="level4">
<h4 class="anchored" data-anchor-id="data-preparation-1">Data Preparation</h4>
<p>As with the <code>Home_Student</code> dataset, the data preparation for the <code>Teacher_Student</code> dataset started with renaming the original variables with more descriptive names. After this, the dataset is cleaned by removing any rows containing missing values resulting in a final dataset with only complete cases as well as specifying categorical variables and dropping any unused levels.</p>
</section>
<section id="descriptive-statistics-1" class="level4">
<h4 class="anchored" data-anchor-id="descriptive-statistics-1">Descriptive Statistics</h4>
<p>The total sample size of the Canada and U.S.A. 4th grade was 26293. However, due to non-response, the sample size used for this analysis was 18194; 15612 females, 2430 males and 152 other. The average math percent score for the 4th grade students were similar for male (M = 50.4, S.D. = 24.4) and female teachers (M = 50.4, S.D. = 24.1) with “other” having a relatively lower average (M = 45.5, S.D. = 23.7) (see <a href="#fig-tch-dist-of-math-score-age-sex-educ-4" class="quarto-xref">Figure&nbsp;8 (d)</a>). A majority of the teachers (93.5%) were between 25 - 59 years old with the rest being under 25 years (3.8%) or over 60 years (2.7%). With regards to the level of formal education, 69.1% of the teachers had a bachelor’s degree or equivalent followed by those with a master’s degree or equivalent at 30.4%. As shown in <a href="#fig-tch-age-by-education" class="quarto-xref">Figure&nbsp;7</a>, only teachers between 30 - 39 years and 50 - 59 years had PhD’s or equivalent. <a href="#tbl-tch-sample-descriptives" class="quarto-xref">Table&nbsp;4</a> provides a comprehensive summary of the descriptive statistics of the sample. As another aim of this analysis is to identify differences in students performance based on a teacher’s level of education and age, these variables were further investigated through graphical representations. From <a href="#fig-tch-dist-of-math-score-age-sex-educ-1" class="quarto-xref">Figure&nbsp;8 (a)</a>, students who were taught by teachers with at least higher levels of formal education - particularly those with a master’s or doctoral degrees- tend to have a slightly higher median score across most of the age groups with the exception of doctoral degree holders between 30 - 39 years. It can also be seen that some subgroups had few to no data points with one subgroup having an outlier. Also, student percentage scores seem relatively consistent across the various teacher age group. Students taught by teachers under 25 years or above 60 years have a slightly higher median score (<a href="#fig-tch-dist-of-math-score-age-sex-educ-2" class="quarto-xref">Figure&nbsp;8 (b)</a>). Also, the median scores for the 4th grade students as well as the overall score distribution tend to increase with higher formal education levels (<a href="#fig-tch-dist-of-math-score-age-sex-educ-3" class="quarto-xref">Figure&nbsp;8 (c)</a>). This suggests a positive association between teacher qualifications and percent correct. As can be seen in <a href="#fig-tch-Correlations" class="quarto-xref">Figure&nbsp;9</a>, all the predictors have a low positive association with the dependent variable. There are also a few predictors that have a moderate positive relationship with each other. The variance inflation factor will be examined to ensure there is no multicollinearity among the predictors. The lack of a strong association with the dependent variable suggests there may be better factors to explain the variation in math percentage scores.</p>
<div class="cell">
<div id="tbl-tch-sample-descriptives" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tch-sample-descriptives-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Sample Descriptive Statistics for Teacher Dataset
</figcaption>
<div aria-describedby="tbl-tch-sample-descriptives-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="Rtable1">
<table class="Rtable1 do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th class="rowlabel firstrow lastrow" data-quarto-table-cell-role="th"></th>
<th class="firstrow lastrow" data-quarto-table-cell-role="th"><span class="stratlabel">Female<br>
<span class="stratn">(N=15612)</span></span></th>
<th class="firstrow lastrow" data-quarto-table-cell-role="th"><span class="stratlabel">Male<br>
<span class="stratn">(N=2430)</span></span></th>
<th class="firstrow lastrow" data-quarto-table-cell-role="th"><span class="stratlabel">Other<br>
<span class="stratn">(N=152)</span></span></th>
<th class="firstrow lastrow" data-quarto-table-cell-role="th"><span class="stratlabel">Overall<br>
<span class="stratn">(N=18194)</span></span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowlabel firstrow">Mathematics Percent Correct Points Scored</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Mean (SD)</td>
<td>50.4 (24.1)</td>
<td>50.4 (24.4)</td>
<td>45.5 (23.7)</td>
<td>50.4 (24.1)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">50.0 [0, 100]</td>
<td class="lastrow">50.0 [0, 100]</td>
<td class="lastrow">42.3 [5.26, 96.3]</td>
<td class="lastrow">50.0 [0, 100]</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow">Age of Teacher</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Under 25</td>
<td>660 (4.2%)</td>
<td>23 (0.9%)</td>
<td>0 (0%)</td>
<td>683 (3.8%)</td>
</tr>
<tr class="even">
<td class="rowlabel">25–29</td>
<td>2020 (12.9%)</td>
<td>200 (8.2%)</td>
<td>13 (8.6%)</td>
<td>2233 (12.3%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">30–39</td>
<td>4154 (26.6%)</td>
<td>557 (22.9%)</td>
<td>45 (29.6%)</td>
<td>4756 (26.1%)</td>
</tr>
<tr class="even">
<td class="rowlabel">40–49</td>
<td>5100 (32.7%)</td>
<td>795 (32.7%)</td>
<td>45 (29.6%)</td>
<td>5940 (32.6%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">50–59</td>
<td>3357 (21.5%)</td>
<td>711 (29.3%)</td>
<td>21 (13.8%)</td>
<td>4089 (22.5%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">60 or more</td>
<td class="lastrow">321 (2.1%)</td>
<td class="lastrow">144 (5.9%)</td>
<td class="lastrow">28 (18.4%)</td>
<td class="lastrow">493 (2.7%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Sex of Teacher</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Female</td>
<td>15612 (100%)</td>
<td>0 (0%)</td>
<td>0 (0%)</td>
<td>15612 (85.8%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">Male</td>
<td>0 (0%)</td>
<td>2430 (100%)</td>
<td>0 (0%)</td>
<td>2430 (13.4%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Other</td>
<td class="lastrow">0 (0%)</td>
<td class="lastrow">0 (0%)</td>
<td class="lastrow">152 (100%)</td>
<td class="lastrow">152 (0.8%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Level of Formal Education Completed</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Post-secondary, non-tertiary education</td>
<td>9 (0.1%)</td>
<td>0 (0%)</td>
<td>0 (0%)</td>
<td>9 (0.0%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">Short-cycle tertiary education</td>
<td>6 (0.0%)</td>
<td>0 (0%)</td>
<td>0 (0%)</td>
<td>6 (0.0%)</td>
</tr>
<tr class="even">
<td class="rowlabel">Bachelor’s or equivalent</td>
<td>10894 (69.8%)</td>
<td>1525 (62.8%)</td>
<td>151 (99.3%)</td>
<td>12570 (69.1%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">Master’s or equivalent</td>
<td>4661 (29.9%)</td>
<td>866 (35.6%)</td>
<td>1 (0.7%)</td>
<td>5528 (30.4%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Doctor or equivalent</td>
<td class="lastrow">42 (0.3%)</td>
<td class="lastrow">39 (1.6%)</td>
<td class="lastrow">0 (0%)</td>
<td class="lastrow">81 (0.4%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Years of Teaching</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Mean (SD)</td>
<td>14.1 (8.70)</td>
<td>15.9 (8.78)</td>
<td>17.2 (10.0)</td>
<td>14.4 (8.75)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">14.0 [1.00, 43.0]</td>
<td class="lastrow">16.0 [1.00, 37.0]</td>
<td class="lastrow">17.0 [1.00, 40.0]</td>
<td class="lastrow">14.0 [1.00, 43.0]</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow">Number of Students in Class</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Mean (SD)</td>
<td>23.6 (5.88)</td>
<td>24.3 (5.35)</td>
<td>22.8 (4.13)</td>
<td>23.7 (5.80)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">24.0 [1.00, 117]</td>
<td class="lastrow">25.0 [4.00, 46.0]</td>
<td class="lastrow">25.0 [14.0, 27.0]</td>
<td class="lastrow">24.0 [1.00, 117]</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Homework Frequency</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">I do not assign mathematics homework</td>
<td>5146 (33.0%)</td>
<td>767 (31.6%)</td>
<td>56 (36.8%)</td>
<td>5969 (32.8%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">Less than once a week</td>
<td>3166 (20.3%)</td>
<td>400 (16.5%)</td>
<td>47 (30.9%)</td>
<td>3613 (19.9%)</td>
</tr>
<tr class="even">
<td class="rowlabel">1 or 2 times a week</td>
<td>3931 (25.2%)</td>
<td>440 (18.1%)</td>
<td>13 (8.6%)</td>
<td>4384 (24.1%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">3 or 4 times a week</td>
<td>2193 (14.0%)</td>
<td>500 (20.6%)</td>
<td>20 (13.2%)</td>
<td>2713 (14.9%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Every day</td>
<td class="lastrow">1176 (7.5%)</td>
<td class="lastrow">323 (13.3%)</td>
<td class="lastrow">16 (10.5%)</td>
<td class="lastrow">1515 (8.3%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">School Emphasis on Teacher's Academic Success</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Mean (SD)</td>
<td>9.90 (2.17)</td>
<td>10.2 (2.65)</td>
<td>9.17 (3.33)</td>
<td>9.93 (2.26)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">9.72 [4.33, 17.0]</td>
<td class="lastrow">10.1 [0.698, 17.0]</td>
<td class="lastrow">8.27 [5.70, 17.0]</td>
<td class="lastrow">9.72 [0.698, 17.0]</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow">Safe and Orderly Schools-Teacher</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Mean (SD)</td>
<td>9.45 (2.23)</td>
<td>9.68 (2.30)</td>
<td>7.89 (2.35)</td>
<td>9.46 (2.24)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">9.32 [4.16, 13.1]</td>
<td class="lastrow">9.32 [4.16, 13.1]</td>
<td class="lastrow">7.86 [4.16, 13.1]</td>
<td class="lastrow">9.32 [4.16, 13.1]</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Teachers Job Satisfaction</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Mean (SD)</td>
<td>9.41 (2.14)</td>
<td>9.68 (2.14)</td>
<td>9.80 (2.25)</td>
<td>9.45 (2.14)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">9.59 [4.59, 12.3]</td>
<td class="lastrow">9.59 [4.59, 12.3]</td>
<td class="lastrow">9.05 [6.29, 12.3]</td>
<td class="lastrow">9.59 [4.59, 12.3]</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow">Teaching Limited by Student Not Ready</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Mean (SD)</td>
<td>9.00 (1.66)</td>
<td>9.24 (1.68)</td>
<td>8.70 (1.10)</td>
<td>9.03 (1.66)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">8.86 [3.23, 15.2]</td>
<td class="lastrow">8.86 [4.75, 15.2]</td>
<td class="lastrow">9.33 [6.65, 13.6]</td>
<td class="lastrow">8.86 [3.23, 15.2]</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow">Teachers Majored in Education and Mathematics</td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Major in Edu and Math</td>
<td>1856 (11.9%)</td>
<td>438 (18.0%)</td>
<td>47 (30.9%)</td>
<td>2341 (12.9%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">Major in Edu but not Math</td>
<td>11429 (73.2%)</td>
<td>1440 (59.3%)</td>
<td>64 (42.1%)</td>
<td>12933 (71.1%)</td>
</tr>
<tr class="even">
<td class="rowlabel">Major in Math but not Edu</td>
<td>264 (1.7%)</td>
<td>86 (3.5%)</td>
<td>0 (0%)</td>
<td>350 (1.9%)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">All other Majors</td>
<td class="lastrow">2063 (13.2%)</td>
<td class="lastrow">466 (19.2%)</td>
<td class="lastrow">41 (27.0%)</td>
<td class="lastrow">2570 (14.1%)</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tch-age-by-education" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tch-age-by-education-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-tch-age-by-education-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tch-age-by-education-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Number of Teachers by Age and Education Level
</figcaption>
</figure>
</div>
</div>
</div>
<div id="fig-tch-dist-of-math-score-age-sex-educ" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tch-dist-of-math-score-age-sex-educ-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-tch-dist-of-math-score-age-sex-educ" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-tch-dist-of-math-score-age-sex-educ-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-tch-dist-of-math-score-age-sex-educ-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-tch-dist-of-math-score-age-sex-educ-1.png" class="img-fluid figure-img" data-ref-parent="fig-tch-dist-of-math-score-age-sex-educ" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-tch-dist-of-math-score-age-sex-educ-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Boxplots of Students’ Math Scores by Teachers Age and Education Level
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-tch-dist-of-math-score-age-sex-educ" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-tch-dist-of-math-score-age-sex-educ-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-tch-dist-of-math-score-age-sex-educ-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-tch-dist-of-math-score-age-sex-educ-2.png" class="img-fluid figure-img" data-ref-parent="fig-tch-dist-of-math-score-age-sex-educ" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-tch-dist-of-math-score-age-sex-educ-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Boxplots of Students’ Math Scores by Age of Teachers
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-tch-dist-of-math-score-age-sex-educ" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-tch-dist-of-math-score-age-sex-educ-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-tch-dist-of-math-score-age-sex-educ-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-tch-dist-of-math-score-age-sex-educ-3.png" class="img-fluid figure-img" data-ref-parent="fig-tch-dist-of-math-score-age-sex-educ" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-tch-dist-of-math-score-age-sex-educ-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Boxplots of Scores Students’ Math Scores by Teacher’s Level of Education
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-tch-dist-of-math-score-age-sex-educ" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-tch-dist-of-math-score-age-sex-educ-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-tch-dist-of-math-score-age-sex-educ-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-tch-dist-of-math-score-age-sex-educ-4.png" class="img-fluid figure-img" data-ref-parent="fig-tch-dist-of-math-score-age-sex-educ" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-tch-dist-of-math-score-age-sex-educ-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Boxplots of Students’ Math Scores by Sex of Teachers
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tch-dist-of-math-score-age-sex-educ-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Boxplots of the Students’ Scores by Age, Education Level and Sex
</figcaption>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tch-Correlations" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tch-Correlations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-tch-Correlations-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tch-Correlations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Correlation Heatmap for Teacher-Level Analysis
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="regression-analysis-1" class="level4">
<h4 class="anchored" data-anchor-id="regression-analysis-1">Regression Analysis</h4>
<p>A step-wise regression model was estimated to evaluate whether the independent variables <em>(Years_Teaching, Sex, Age, Formal_Educ, Class_Size, Homework_Freq, Academic_Success, Safe_Orderly_Schools, Job_Satis, Student_not_Ready, Math_Major and Instruction_Hours)</em> could predict the dependent variable, <em>Math_Percent_Correct</em> . The linear relationship between independent variables and math score was found to be statistically significant <span class="math inline">\(F(25, 18168) = 35.51,\ p &lt; .001\)</span>, but it explained a small proportion of variance in students’ math percentage scores. <span class="math inline">\((R^2 = .05,\ R^2_{adj}=.05)\)</span>. Among the predictors, instructional clarity had a statistically non-significant and negative effect on math percentage value <span class="math inline">\((\beta = -.16,\ p &lt; .001)\)</span>, suggesting that greater instructional clarity was not associated with higher math percent values in this model over and above all other predictors. Compared to teachers with post-secondary, non-tertiary education, the effect of holding a bachelor’s or equivalent degree was statistically significant and positive <span class="math inline">\((\beta = 15.93,\ p = .043)\)</span>, as were the effects of holding a master’s or equivalent <span class="math inline">\((\beta = 17.16,\ p = .030)\)</span> and a doctoral or equivalent degree <span class="math inline">\((\beta = 17.54,\ p = .035)\)</span>. The effect of holding a short-cycle tertiary education degree was positive but not statistically significant <span class="math inline">\((\beta = 6.47,\ p = .603)\)</span>. Relative to teachers under 25, the effects of being aged 25–29 <span class="math inline">\((\beta = -4.21,\ p &lt; .001)\)</span>, 30–39 <span class="math inline">\((\beta = -4.80,\ p &lt; .001)\)</span>, 40–49 <span class="math inline">\((\beta = -4.44,\ p &lt; .001)\)</span>, and 50–59 <span class="math inline">\((\beta = -4.59,\ p &lt; .001)\)</span> were statistically significant and negative. The effect of being aged 60 or more was negative but not statistically significant <span class="math inline">\((\beta = -1.79,\ p = .266)\)</span>. Regarding the the other predictors, Years of teaching experience, class size, homework frequency (excluding “less than once a week”), academic success, and student readiness had statistically significant effects. In contrast, the effects of sex, instruction hours, and most math major categories were not statistically significant. The details of the results from the step-wise analysis are presented in <a href="#tbl-tch-Initial-regression-for-teacher-data-1" class="quarto-xref">Table&nbsp;5 (a)</a> and <a href="#tbl-tch-Initial-regression-for-teacher-data-2" class="quarto-xref">Table&nbsp;5 (b)</a>. The categories of formal education levels had the largest effect on students’ math percentage scores <a href="#tbl-tch-Initial-regression-for-teacher-data-4" class="quarto-xref">Table&nbsp;5 (d)</a>. The predictors used in this analysis do not exhibit multicollinearity as shown in <a href="#tbl-tch-Initial-regression-for-teacher-data-3" class="quarto-xref">Table&nbsp;5 (c)</a>.</p>
<p>The “Residuals vs Fitted” plot in <a href="#fig-tch-residual" class="quarto-xref">Figure&nbsp;10</a> shows that the residuals are approximately symmetrically distributed around zero across the range of fitted values, although there is a slight funnel shape, suggesting mild heteroscedasticity. From the Q-Q plot, some deviations from the diagonal line can be seen particularly at the tails suggesting slight departures from normality. A look at the “Scale-Location” plot reveals a fairly consistent spread of the standardized residuals with a slight vurvature at the extremes suggesting some heteroscedasticity. The “Residuals vs Leverage” plot also exhibited a few cases with high leverage nut a majority of observations were within an acceptable leverage range. Overall, a linear regression model seems adequate as the assumptions have been met to a large extent.</p>
<div class="cell">
<div id="tbl-tch-Initial-regression-for-teacher-data" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tch-Initial-regression-for-teacher-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Teacher-Level Regression Analysis
</figcaption>
<div aria-describedby="tbl-tch-Initial-regression-for-teacher-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="tbl-tch-Initial-regression-for-teacher-data-1" class="table table-striped table-hover table-condensed do-not-create-environment quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-tch-Initial-regression-for-teacher-data-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Teacher Level Regression Coefficients
</figcaption>
<div aria-describedby="tbl-tch-Initial-regression-for-teacher-data-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-tch-Initial-regression-for-teacher-data-1" class="table table-striped table-hover table-condensed do-not-create-environment caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">10.629</td>
<td style="text-align: right;">8.066</td>
<td style="text-align: right;">1.318</td>
<td style="text-align: right;">0.188</td>
</tr>
<tr class="even">
<td style="text-align: left;">Years_Teaching</td>
<td style="text-align: right;">0.126</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">3.630</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SexMale</td>
<td style="text-align: right;">-0.954</td>
<td style="text-align: right;">0.524</td>
<td style="text-align: right;">-1.821</td>
<td style="text-align: right;">0.069</td>
</tr>
<tr class="even">
<td style="text-align: left;">SexOther</td>
<td style="text-align: right;">-2.961</td>
<td style="text-align: right;">1.946</td>
<td style="text-align: right;">-1.521</td>
<td style="text-align: right;">0.128</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age25–29</td>
<td style="text-align: right;">-4.207</td>
<td style="text-align: right;">1.040</td>
<td style="text-align: right;">-4.043</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age30–39</td>
<td style="text-align: right;">-4.796</td>
<td style="text-align: right;">1.012</td>
<td style="text-align: right;">-4.740</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age40–49</td>
<td style="text-align: right;">-4.445</td>
<td style="text-align: right;">1.103</td>
<td style="text-align: right;">-4.030</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age50–59</td>
<td style="text-align: right;">-4.594</td>
<td style="text-align: right;">1.266</td>
<td style="text-align: right;">-3.627</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age60 or more</td>
<td style="text-align: right;">-1.792</td>
<td style="text-align: right;">1.612</td>
<td style="text-align: right;">-1.112</td>
<td style="text-align: right;">0.266</td>
</tr>
<tr class="even">
<td style="text-align: left;">Formal_EducShort-cycle tertiary education</td>
<td style="text-align: right;">6.473</td>
<td style="text-align: right;">12.460</td>
<td style="text-align: right;">0.519</td>
<td style="text-align: right;">0.603</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Formal_EducBachelor’s or equivalent</td>
<td style="text-align: right;">15.930</td>
<td style="text-align: right;">7.878</td>
<td style="text-align: right;">2.022</td>
<td style="text-align: right;">0.043</td>
</tr>
<tr class="even">
<td style="text-align: left;">Formal_EducMaster’s or equivalent</td>
<td style="text-align: right;">17.157</td>
<td style="text-align: right;">7.884</td>
<td style="text-align: right;">2.176</td>
<td style="text-align: right;">0.030</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Formal_EducDoctor or equivalent</td>
<td style="text-align: right;">17.543</td>
<td style="text-align: right;">8.317</td>
<td style="text-align: right;">2.109</td>
<td style="text-align: right;">0.035</td>
</tr>
<tr class="even">
<td style="text-align: left;">Class_Size</td>
<td style="text-align: right;">0.189</td>
<td style="text-align: right;">0.031</td>
<td style="text-align: right;">6.099</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Homework_FreqLess than once a week</td>
<td style="text-align: right;">0.458</td>
<td style="text-align: right;">0.501</td>
<td style="text-align: right;">0.915</td>
<td style="text-align: right;">0.360</td>
</tr>
<tr class="even">
<td style="text-align: left;">Homework_Freq1 or 2 times a week</td>
<td style="text-align: right;">3.250</td>
<td style="text-align: right;">0.474</td>
<td style="text-align: right;">6.853</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Homework_Freq3 or 4 times a week</td>
<td style="text-align: right;">2.174</td>
<td style="text-align: right;">0.566</td>
<td style="text-align: right;">3.842</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Homework_FreqEvery day</td>
<td style="text-align: right;">2.930</td>
<td style="text-align: right;">0.700</td>
<td style="text-align: right;">4.185</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Academic_Success</td>
<td style="text-align: right;">1.574</td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">15.644</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Safe_Orderly_Schools</td>
<td style="text-align: right;">-0.366</td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">-3.604</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Job_Satis</td>
<td style="text-align: right;">-0.644</td>
<td style="text-align: right;">0.093</td>
<td style="text-align: right;">-6.941</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Student_not_Ready</td>
<td style="text-align: right;">1.376</td>
<td style="text-align: right;">0.125</td>
<td style="text-align: right;">11.039</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Math_MajorMajor in Edu but not Math</td>
<td style="text-align: right;">1.014</td>
<td style="text-align: right;">0.540</td>
<td style="text-align: right;">1.880</td>
<td style="text-align: right;">0.060</td>
</tr>
<tr class="even">
<td style="text-align: left;">Math_MajorMajor in Math but not Edu</td>
<td style="text-align: right;">4.197</td>
<td style="text-align: right;">1.365</td>
<td style="text-align: right;">3.075</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Math_MajorAll other Majors</td>
<td style="text-align: right;">-0.213</td>
<td style="text-align: right;">0.681</td>
<td style="text-align: right;">-0.312</td>
<td style="text-align: right;">0.755</td>
</tr>
<tr class="even">
<td style="text-align: left;">Instruction_Hours</td>
<td style="text-align: right;">0.159</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;">1.667</td>
<td style="text-align: right;">0.096</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</div>
<div class="cell-output-display">
<div id="tbl-tch-Initial-regression-for-teacher-data-2" class="table table-striped table-hover table-condensed do-not-create-environment quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-tch-Initial-regression-for-teacher-data-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Teacher Level Model Summary Statistics
</figcaption>
<div aria-describedby="tbl-tch-Initial-regression-for-teacher-data-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-tch-Initial-regression-for-teacher-data-2" class="table table-striped table-hover table-condensed do-not-create-environment caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">adj.r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.047</td>
<td style="text-align: right;">0.045</td>
<td style="text-align: right;">23.553</td>
<td style="text-align: right;">35.505</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">-83282.86</td>
<td style="text-align: right;">166619.7</td>
<td style="text-align: right;">166830.6</td>
<td style="text-align: right;">10078858</td>
<td style="text-align: right;">18168</td>
<td style="text-align: right;">18194</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</div>
<div class="cell-output-display">
<div id="tbl-tch-Initial-regression-for-teacher-data-3" class="table table-striped table-hover table-condensed do-not-create-environment quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-tch-Initial-regression-for-teacher-data-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Variance Inflation Factors for Teacher Level Analysis
</figcaption>
<div aria-describedby="tbl-tch-Initial-regression-for-teacher-data-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-tch-Initial-regression-for-teacher-data-3" class="table table-striped table-hover table-condensed do-not-create-environment caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">GVIF</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">GVIF^(1/(2*Df))</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Years_Teaching</td>
<td style="text-align: right;">3.047</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.746</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sex</td>
<td style="text-align: right;">1.069</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.017</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">3.345</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.128</td>
</tr>
<tr class="even">
<td style="text-align: left;">Formal_Educ</td>
<td style="text-align: right;">1.122</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.014</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Class_Size</td>
<td style="text-align: right;">1.059</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.029</td>
</tr>
<tr class="even">
<td style="text-align: left;">Homework_Freq</td>
<td style="text-align: right;">1.205</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.024</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Academic_Success</td>
<td style="text-align: right;">1.693</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.301</td>
</tr>
<tr class="even">
<td style="text-align: left;">Safe_Orderly_Schools</td>
<td style="text-align: right;">1.699</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.304</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Job_Satis</td>
<td style="text-align: right;">1.297</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.139</td>
</tr>
<tr class="even">
<td style="text-align: left;">Student_not_Ready</td>
<td style="text-align: right;">1.407</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.186</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Math_Major</td>
<td style="text-align: right;">1.129</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1.020</td>
</tr>
<tr class="even">
<td style="text-align: left;">Instruction_Hours</td>
<td style="text-align: right;">1.057</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.028</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</div>
<div class="cell-output-display">
<div id="tbl-tch-Initial-regression-for-teacher-data-4" class="table table-striped table-hover table-condensed do-not-create-environment quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-tch-Initial-regression-for-teacher-data-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Standardized Regression Coefficients for Teacher Level Analysis
</figcaption>
<div aria-describedby="tbl-tch-Initial-regression-for-teacher-data-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-tch-Initial-regression-for-teacher-data-4" class="table table-striped table-hover table-condensed do-not-create-environment caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">-0.292</td>
</tr>
<tr class="even">
<td style="text-align: left;">Years_Teaching</td>
<td style="text-align: right;">0.046</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sex_Male</td>
<td style="text-align: right;">-0.020</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sex_Other</td>
<td style="text-align: right;">-0.061</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age(25–29)</td>
<td style="text-align: right;">-0.087</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age (30–39)</td>
<td style="text-align: right;">-0.099</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age (40–49)</td>
<td style="text-align: right;">-0.092</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age (50–59)</td>
<td style="text-align: right;">-0.095</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age (60 or more)</td>
<td style="text-align: right;">-0.037</td>
</tr>
<tr class="even">
<td style="text-align: left;">Formal_Educ (Short-cycle tertiary education)</td>
<td style="text-align: right;">0.134</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Formal_Educ (Bachelor’s or equivalent)</td>
<td style="text-align: right;">0.330</td>
</tr>
<tr class="even">
<td style="text-align: left;">Formal_Educ (Master’s or equivalent)</td>
<td style="text-align: right;">0.356</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Formal_Educ (Doctor or equivalent)</td>
<td style="text-align: right;">0.364</td>
</tr>
<tr class="even">
<td style="text-align: left;">Class_Size</td>
<td style="text-align: right;">0.045</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Homework_Freq (Less than once a week)</td>
<td style="text-align: right;">0.010</td>
</tr>
<tr class="even">
<td style="text-align: left;">Homework_Freq (1 or 2 times a week)</td>
<td style="text-align: right;">0.067</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Homework_Freq (3 or 4 times a week)</td>
<td style="text-align: right;">0.045</td>
</tr>
<tr class="even">
<td style="text-align: left;">Homework_Freq (Every day)</td>
<td style="text-align: right;">0.061</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Academic_Success</td>
<td style="text-align: right;">0.147</td>
</tr>
<tr class="even">
<td style="text-align: left;">Safe_Orderly_Schools</td>
<td style="text-align: right;">-0.034</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Job_Satis</td>
<td style="text-align: right;">-0.057</td>
</tr>
<tr class="even">
<td style="text-align: left;">Student_not_Ready</td>
<td style="text-align: right;">0.095</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Math_Major (Major in Edu but not Math)</td>
<td style="text-align: right;">0.021</td>
</tr>
<tr class="even">
<td style="text-align: left;">Math_Major (Major in Math but not Edu)</td>
<td style="text-align: right;">0.087</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Math_Major(All other Majors)</td>
<td style="text-align: right;">-0.004</td>
</tr>
<tr class="even">
<td style="text-align: left;">Instruction_Hours</td>
<td style="text-align: right;">0.012</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tch-residual" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tch-residual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-tch-residual-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tch-residual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Residual Plots for the Teacher-Level Regression Model
</figcaption>
</figure>
</div>
</div>
</div>
<section id="marginal-contrast-analysis" class="level5">
<h5 class="anchored" data-anchor-id="marginal-contrast-analysis">Marginal Contrast Analysis</h5>
<p>Following the significant effect of the variables age and level of formal education in the regression model, the marginal means for these variables were computed separately, holding all other variables at their mean values. This was done to examine whether the model estimated different math test scores for an average student who had a teacher in any of the categories of age or formal education, respectively. A visualization of these estimated means is provided in <a href="#fig-tch-marginal-contrast-analysis" class="quarto-xref">Figure&nbsp;11</a>, which shows distinct predictions at each subgroup.</p>
<p>For the variable age, a marginal contrast analysis, revealed statistically significant differences in student scores between nearly all age categories and the reference group (teachers under 25 years), except for those above 60 years. Students with teachers under the age of 25 appeared to score approximately 4.20% to 4.80% higher than their peers.</p>
<p>A separate analysis was performed for level of formal education, again while holding all other variables at their means. This analysis found a statistically significant difference was observed between between students whose teachers held a master’s degree or equivalent and those whose teachers held a bachelor’s degree or equivalent. No other pairwise comparison had statistically significant results.</p>
<p>In both analyses, Bonferroni-adjusted p-values were reported to account for multiple comparisons. Full results of these two analyses are presented in <a href="#tbl-tch-marginal-contrast-analysis" class="quarto-xref">Table&nbsp;6</a>.</p>
<div id="fig-tch-marginal-contrast-analysis" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tch-marginal-contrast-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-tch-marginal-contrast-analysis" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-tch-marginal-contrast-analysis-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-tch-marginal-contrast-analysis-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-tch-marginal-contrast-analysis-1.png" class="img-fluid figure-img" data-ref-parent="fig-tch-marginal-contrast-analysis" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-tch-marginal-contrast-analysis-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Estimated Marginal Means by Age Group
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-tch-marginal-contrast-analysis" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-tch-marginal-contrast-analysis-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-tch-marginal-contrast-analysis-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ESRM-6990V_files/figure-html/fig-tch-marginal-contrast-analysis-2.png" class="img-fluid figure-img" data-ref-parent="fig-tch-marginal-contrast-analysis" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-tch-marginal-contrast-analysis-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Estimated Marginal Means by Level of Formal Education
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tch-marginal-contrast-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Plots of Estimated Marginal Means
</figcaption>
</figure>
</div>
<div class="cell">
<div id="tbl-tch-marginal-contrast-analysis" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tch-marginal-contrast-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Marginal Contrast Analysis
</figcaption>
<div aria-describedby="tbl-tch-marginal-contrast-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Level1
</th>
<th style="text-align:left;">
Level2
</th>
<th style="text-align:right;">
Difference
</th>
<th style="text-align:right;">
SE
</th>
<th style="text-align:right;">
CI_low
</th>
<th style="text-align:right;">
CI_high
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
25–29
</td>
<td style="text-align:left;">
Under 25
</td>
<td style="text-align:right;">
-4.207
</td>
<td style="text-align:right;">
1.040
</td>
<td style="text-align:right;">
-6.247
</td>
<td style="text-align:right;">
-2.168
</td>
<td style="text-align:right;">
-4.043
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
30–39
</td>
<td style="text-align:left;">
Under 25
</td>
<td style="text-align:right;">
-4.796
</td>
<td style="text-align:right;">
1.012
</td>
<td style="text-align:right;">
-6.780
</td>
<td style="text-align:right;">
-2.813
</td>
<td style="text-align:right;">
-4.740
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
40–49
</td>
<td style="text-align:left;">
Under 25
</td>
<td style="text-align:right;">
-4.445
</td>
<td style="text-align:right;">
1.103
</td>
<td style="text-align:right;">
-6.607
</td>
<td style="text-align:right;">
-2.283
</td>
<td style="text-align:right;">
-4.030
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
50–59
</td>
<td style="text-align:left;">
Under 25
</td>
<td style="text-align:right;">
-4.594
</td>
<td style="text-align:right;">
1.266
</td>
<td style="text-align:right;">
-7.076
</td>
<td style="text-align:right;">
-2.111
</td>
<td style="text-align:right;">
-3.627
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
0.004
</td>
</tr>
<tr>
<td style="text-align:left;">
60 or more
</td>
<td style="text-align:left;">
Under 25
</td>
<td style="text-align:right;">
-1.792
</td>
<td style="text-align:right;">
1.612
</td>
<td style="text-align:right;">
-4.951
</td>
<td style="text-align:right;">
1.368
</td>
<td style="text-align:right;">
-1.112
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
30–39
</td>
<td style="text-align:left;">
25–29
</td>
<td style="text-align:right;">
-0.589
</td>
<td style="text-align:right;">
0.635
</td>
<td style="text-align:right;">
-1.833
</td>
<td style="text-align:right;">
0.655
</td>
<td style="text-align:right;">
-0.928
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
40–49
</td>
<td style="text-align:left;">
25–29
</td>
<td style="text-align:right;">
-0.238
</td>
<td style="text-align:right;">
0.738
</td>
<td style="text-align:right;">
-1.684
</td>
<td style="text-align:right;">
1.208
</td>
<td style="text-align:right;">
-0.322
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
50–59
</td>
<td style="text-align:left;">
25–29
</td>
<td style="text-align:right;">
-0.387
</td>
<td style="text-align:right;">
0.943
</td>
<td style="text-align:right;">
-2.235
</td>
<td style="text-align:right;">
1.462
</td>
<td style="text-align:right;">
-0.410
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
60 or more
</td>
<td style="text-align:left;">
25–29
</td>
<td style="text-align:right;">
2.415
</td>
<td style="text-align:right;">
1.374
</td>
<td style="text-align:right;">
-0.279
</td>
<td style="text-align:right;">
5.109
</td>
<td style="text-align:right;">
1.757
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
40–49
</td>
<td style="text-align:left;">
30–39
</td>
<td style="text-align:right;">
0.351
</td>
<td style="text-align:right;">
0.529
</td>
<td style="text-align:right;">
-0.685
</td>
<td style="text-align:right;">
1.388
</td>
<td style="text-align:right;">
0.665
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
50–59
</td>
<td style="text-align:left;">
30–39
</td>
<td style="text-align:right;">
0.203
</td>
<td style="text-align:right;">
0.725
</td>
<td style="text-align:right;">
-1.219
</td>
<td style="text-align:right;">
1.624
</td>
<td style="text-align:right;">
0.279
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
60 or more
</td>
<td style="text-align:left;">
30–39
</td>
<td style="text-align:right;">
3.004
</td>
<td style="text-align:right;">
1.240
</td>
<td style="text-align:right;">
0.575
</td>
<td style="text-align:right;">
5.434
</td>
<td style="text-align:right;">
2.424
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
0.231
</td>
</tr>
<tr>
<td style="text-align:left;">
50–59
</td>
<td style="text-align:left;">
40–49
</td>
<td style="text-align:right;">
-0.149
</td>
<td style="text-align:right;">
0.549
</td>
<td style="text-align:right;">
-1.225
</td>
<td style="text-align:right;">
0.927
</td>
<td style="text-align:right;">
-0.271
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
60 or more
</td>
<td style="text-align:left;">
40–49
</td>
<td style="text-align:right;">
2.653
</td>
<td style="text-align:right;">
1.148
</td>
<td style="text-align:right;">
0.402
</td>
<td style="text-align:right;">
4.904
</td>
<td style="text-align:right;">
2.310
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
0.313
</td>
</tr>
<tr>
<td style="text-align:left;">
60 or more
</td>
<td style="text-align:left;">
50–59
</td>
<td style="text-align:right;">
2.802
</td>
<td style="text-align:right;">
1.141
</td>
<td style="text-align:right;">
0.566
</td>
<td style="text-align:right;">
5.038
</td>
<td style="text-align:right;">
2.456
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
0.211
</td>
</tr>
</tbody>
</table>
<p>Marginal Contrast Analysis by Age Group</p>
</div>
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Level1
</th>
<th style="text-align:left;">
Level2
</th>
<th style="text-align:right;">
Difference
</th>
<th style="text-align:right;">
SE
</th>
<th style="text-align:right;">
CI_low
</th>
<th style="text-align:right;">
CI_high
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Short-cycle tertiary education
</td>
<td style="text-align:left;">
Post-secondary, non-tertiary education
</td>
<td style="text-align:right;">
6.473
</td>
<td style="text-align:right;">
12.460
</td>
<td style="text-align:right;">
-17.950
</td>
<td style="text-align:right;">
30.895
</td>
<td style="text-align:right;">
0.519
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Bachelor’s or equivalent
</td>
<td style="text-align:left;">
Post-secondary, non-tertiary education
</td>
<td style="text-align:right;">
15.930
</td>
<td style="text-align:right;">
7.878
</td>
<td style="text-align:right;">
0.487
</td>
<td style="text-align:right;">
31.372
</td>
<td style="text-align:right;">
2.022
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
0.432
</td>
</tr>
<tr>
<td style="text-align:left;">
Master’s or equivalent
</td>
<td style="text-align:left;">
Post-secondary, non-tertiary education
</td>
<td style="text-align:right;">
17.157
</td>
<td style="text-align:right;">
7.884
</td>
<td style="text-align:right;">
1.704
</td>
<td style="text-align:right;">
32.609
</td>
<td style="text-align:right;">
2.176
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
0.295
</td>
</tr>
<tr>
<td style="text-align:left;">
Doctor or equivalent
</td>
<td style="text-align:left;">
Post-secondary, non-tertiary education
</td>
<td style="text-align:right;">
17.543
</td>
<td style="text-align:right;">
8.317
</td>
<td style="text-align:right;">
1.240
</td>
<td style="text-align:right;">
33.845
</td>
<td style="text-align:right;">
2.109
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
0.349
</td>
</tr>
<tr>
<td style="text-align:left;">
Bachelor’s or equivalent
</td>
<td style="text-align:left;">
Short-cycle tertiary education
</td>
<td style="text-align:right;">
9.457
</td>
<td style="text-align:right;">
9.646
</td>
<td style="text-align:right;">
-9.450
</td>
<td style="text-align:right;">
28.364
</td>
<td style="text-align:right;">
0.980
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Master’s or equivalent
</td>
<td style="text-align:left;">
Short-cycle tertiary education
</td>
<td style="text-align:right;">
10.684
</td>
<td style="text-align:right;">
9.650
</td>
<td style="text-align:right;">
-8.231
</td>
<td style="text-align:right;">
29.599
</td>
<td style="text-align:right;">
1.107
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Doctor or equivalent
</td>
<td style="text-align:left;">
Short-cycle tertiary education
</td>
<td style="text-align:right;">
11.070
</td>
<td style="text-align:right;">
9.997
</td>
<td style="text-align:right;">
-8.525
</td>
<td style="text-align:right;">
30.665
</td>
<td style="text-align:right;">
1.107
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Master’s or equivalent
</td>
<td style="text-align:left;">
Bachelor’s or equivalent
</td>
<td style="text-align:right;">
1.227
</td>
<td style="text-align:right;">
0.396
</td>
<td style="text-align:right;">
0.450
</td>
<td style="text-align:right;">
2.004
</td>
<td style="text-align:right;">
3.095
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
0.020
</td>
</tr>
<tr>
<td style="text-align:left;">
Doctor or equivalent
</td>
<td style="text-align:left;">
Bachelor’s or equivalent
</td>
<td style="text-align:right;">
1.613
</td>
<td style="text-align:right;">
2.651
</td>
<td style="text-align:right;">
-3.582
</td>
<td style="text-align:right;">
6.808
</td>
<td style="text-align:right;">
0.609
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Doctor or equivalent
</td>
<td style="text-align:left;">
Master’s or equivalent
</td>
<td style="text-align:right;">
0.386
</td>
<td style="text-align:right;">
2.663
</td>
<td style="text-align:right;">
-4.834
</td>
<td style="text-align:right;">
5.606
</td>
<td style="text-align:right;">
0.145
</td>
<td style="text-align:right;">
18168
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
</tbody>
</table>
<p>Marginal Contrast Analysis by Age Group</p>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
</section>
</section>
<section id="discussion-and-conclusion" class="level2">
<h2 class="anchored" data-anchor-id="discussion-and-conclusion">Discussion and Conclusion</h2>
<p>The analyses of the TIMSS 2023 data for 4th grade students in the U.S.A. and Canada revealed that both teacher-level and student-level characteristics play a statistically significant role in predicting math percentage scores on the TIMSS 2023.</p>
<p>The student-level explained approximately 21% of the variance in test scores, with gender, country, and students’ attitudes toward learning math showing notable effects. Interestingly, a student’s liking for math was unexpectedly negatively associated with their test scores. The difference-in-differences analysis also revealed statististicaally significant differences across combinations of gender and country. Country level differences seem to have alarger effect as an average 4th grade girl in the U.S.A is estimated to score higher than their male and female Canadian counterparts. Despite this, it is important to recognize that country-level differences may reflect broader cultural and systemic factors. Given the distinct educational cultures, curricula, and teaching practices of the U.S. and Canada, attributing differences in scores solely to country-level factors would require further investigation.</p>
<p>The teacher-level analysis accounted for approximately 5% of the variance in student scores. Notably, having an older teacher was negatively correlated with student performance, and having a teacher with a higher level of formal education had a positive effect. The small effect size of the model (5%) suggest that these factors alone explain a modest proportion of variation in a student’s performace on the TIMSS 2023 math test. This highlights that other factors like school resources, classroom dynamics, teaching practices among others may contribute more substantially to a student’s performance. The marginal contrast analysis showed that only the comparison between students of teachers with master’s vs.&nbsp;bachelor’s degrees yielded statistically significant differences. Additionally, students with teachers under 25 years old scored higher than those with teachers from other age groups.</p>
<p>These findings indicate that, while teacher education remains a key factor in student performance, the small expalinaded variations by the models imply that additional factors should be considered in future research. Policymakers and educators may want to focus on improving teacher qualifications, but also recognize that improving teaching quality in broader terms—including pedagogical practices and teacher-student interactions—will likely have a more profound impact on student performance.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-yin2024" class="csl-entry" role="listitem">
Yin, Liqun, and Katherine Reynolds. 2024. <span>“Creating and Interpreting the TIMSS Context Questionnaire Scales.”</span> <a href="https://doi.org/10.6017/lse.tpisc.timss.rs2550">https://doi.org/10.6017/lse.tpisc.timss.rs2550</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>